FROM python:3.11.0

WORKDIR /app
COPY alembic.ini /app/
COPY alembic /app/alembic
COPY requirements.txt /app/
COPY templates /app/templates

RUN pip install --upgrade pip
RUN pip install -r ./requirements.txt
