FROM python:3.11.0

RUN python3 -m pip install uv

WORKDIR /app
COPY alembic.ini /app/
COPY alembic /app/alembic
COPY requirements.txt /app/


RUN uv pip install --system --upgrade pip
RUN uv pip install --system -r ./requirements.txt