"""Added Prompt Prompt Version Table

Revision ID: 7a6a5dc76d63
Revises: b6c2eb9ea3bc
Create Date: 2025-11-13 08:58:26.234908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7a6a5dc76d63'
down_revision: Union[str, None] = 'b6c2eb9ea3bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_version_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['default_version_id'], ['prompt_version.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_name'), 'prompt', ['name'], unique=True)
    op.create_table('prompt_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('deployment_name', sa.String(length=255), nullable=True),
    sa.Column('model_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stream', sa.Boolean(), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('input_validation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_validation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('llm_retry_limit', sa.Integer(), nullable=True),
    sa.Column('enable_tools', sa.Boolean(), nullable=True),
    sa.Column('allow_multiple_calls', sa.Boolean(), nullable=True),
    sa.Column('system_prompt_role', sa.String(length=50), nullable=True),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompt.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_id', 'version', name='uq_prompt_version')
    )
    op.create_index('idx_prompt_version_lookup', 'prompt_version', ['prompt_id', 'version'], unique=False)
    op.create_index(op.f('ix_prompt_version_prompt_id'), 'prompt_version', ['prompt_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_version_prompt_id'), table_name='prompt_version')
    op.drop_index('idx_prompt_version_lookup', table_name='prompt_version')
    op.drop_table('prompt_version')
    op.drop_index(op.f('ix_prompt_name'), table_name='prompt')
    op.drop_table('prompt')
    # ### end Alembic commands ###
