{ lib, modulesPath, ... }:

{
  imports = [
    "${toString modulesPath}/virtualisation/azure-common.nix"
  ];

  facter.reportPath = ./facter.json;
  virtualisation.azure.acceleratedNetworking = true;

  boot.kernelParams = lib.mkForce [
    "console=ttyS0" # azure serial console
    "earlyprintk=ttyS0"
    "rootdelay=300"
    "systemd.setenv=SYSTEMD_SULOGIN_FORCE=1"
  ];

  # this is just lsmod | cut -f1 -d' ' from debian11 -> nixos kexec
  # without the is azure os disk won't shpw up in initrd, and boot fails
  # i don't have time to track down which module is responsible for this
  # feel free to clean this mess
  boot.initrd.kernelModules = [
    "nls_iso8859_1"
    "nls_cp437"
    "vfat"
    "fat"
    "ext4"
    "crc16"
    "mbcache"
    "jbd2"
    "af_packet"
    "cfg80211"
    "rfkill"
    "sch_fq_codel"
    "dm_raid"
    "raid456"
    "async_raid6_recov"
    "async_memcpy"
    "async_pq"
    "async_xor"
    "async_tx"
    "md_mod"
    "xor"
    "raid6_pq"
    "mlx5_ib"
    "ib_uverbs"
    "ib_core"
    "edac_core"
    "intel_rapl_msr"
    "intel_rapl_common"
    "kvm_amd"
    "ccp"
    "rng_core"
    "mlx5_core"
    "kvm"
    "nvme"
    "nvme_core"
    "irqbypass"
    "evdev"
    "mlxfw"
    "nvme_auth"
    "polyval_clmulni"
    "serio_raw"
    "joydev"
    "polyval_generic"
    "ghash_clmulni_intel"
    "atkbd"
    "mousedev"
    "sha512_ssse3"
    "sha256_ssse3"
    "libps2"
    "mac_hid"
    "sha1_ssse3"
    "vivaldi_fmap"
    "hv_utils"
    "hid_generic"
    "aesni_intel"
    "hyperv_keyboard"
    "hid_hyperv"
    "ptp"
    "crypto_simd"
    "hid"
    "pci_hyperv"
    "cryptd"
    "hv_netvsc"
    "rtc_cmos"
    "vmgenid"
    "pps_core"
    "serio"
    "hyperv_drm"
    "hv_balloon"
    "pci_hyperv_intf"
    "fuse"
    "efi_pstore"
    "configfs"
    "nfnetlink"
    "vsock_loopback"
    "vmw_vsock_virtio_transport_common"
    "hv_sock"
    "vmw_vsock_vmci_transport"
    "vsock"
    "vmw_vmci"
    "dmi_sysfs"
    "ip_tables"
    "erofs"
    "squashfs"
    "sr_mod"
    "cdrom"
    "hv_storvsc"
    "scsi_transport_fc"
    "scsi_mod"
    "scsi_common"
    "hv_vmbus"
    "dm_mod"
    "dax"
    "overlay"
    "loop"
    "efivarfs"
    "autofs4"
  ];
}
