FROM python:3.11.0

WORKDIR /app
COPY alembic.ini /app/
COPY alembic /app/alembic
COPY requirements.txt /app/
COPY requirements-dev.txt /app/
COPY requirements-lint.txt /app/
COPY requirements-test.txt /app/


RUN pip install --upgrade pip
RUN pip install -r ./requirements.txt
RUN pip install -r ./requirements-dev.txt