"""add guardrails schema v2

Revision ID: 1433e70d23ab
Revises: e5b3d2a8f92c
Create Date: 2025-09-05 16:15:24.895672

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "1433e70d23ab"
down_revision: Union[str, None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("active", "disabled", "deleted", name="guardrail_status_enum").create(op.get_bind())
    sa.Enum("model", "moderation", name="provider_capability_enum").create(op.get_bind())
    op.create_table(
        "guardrail_probe",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("uri", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM("active", "disabled", "deleted", name="guardrail_status_enum", create_type=False),
            nullable=False,
        ),
        sa.Column("provider_id", sa.Uuid(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "provider_type",
            postgresql.ENUM("cloud", "bud", name="guardrail_provider_type_enum", create_type=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["provider.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uri"),
    )
    op.create_table(
        "guardrail_profile",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("severity_threshold", sa.Float(), nullable=True),
        sa.Column("guard_types", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM("active", "disabled", "deleted", name="guardrail_status_enum", create_type=False),
            nullable=False,
        ),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "guardrail_profile_probe",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("probe_id", sa.Uuid(), nullable=False),
        sa.Column("severity_threshold", sa.Float(), nullable=True),
        sa.Column("guard_types", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(["probe_id"], ["guardrail_probe.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["profile_id"], ["guardrail_profile.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_guardrail_profile_probe_probe_id"), "guardrail_profile_probe", ["probe_id"], unique=False)
    op.create_table(
        "guardrail_rule",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("probe_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("uri", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("examples", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM("active", "disabled", "deleted", name="guardrail_status_enum", create_type=False),
            nullable=False,
        ),
        sa.Column("guard_types", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("scanner_types", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("modality_types", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(["probe_id"], ["guardrail_probe.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uri"),
    )
    op.create_index(op.f("ix_guardrail_rule_probe_id"), "guardrail_rule", ["probe_id"], unique=False)
    op.create_table(
        "guardrail_deployment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "running",
                "failure",
                "deploying",
                "unhealthy",
                "deleting",
                "deleted",
                "pending",
                name="guardrail_deployment_status",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("endpoint_id", sa.Uuid(), nullable=True),
        sa.Column("credential_id", sa.Uuid(), nullable=True),
        sa.Column("severity_threshold", sa.Float(), nullable=True),
        sa.Column("guard_types", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(["endpoint_id"], ["endpoint.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["profile_id"], ["guardrail_profile.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "guardrail_profile_rule",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("profile_probe_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("active", "disabled", "deleted", name="guardrail_status_enum", create_type=False),
            nullable=False,
        ),
        sa.Column("severity_threshold", sa.Float(), nullable=True),
        sa.Column("guard_types", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(["profile_probe_id"], ["guardrail_profile_probe.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["rule_id"], ["guardrail_rule.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_guardrail_profile_rule_rule_id"), "guardrail_profile_rule", ["rule_id"], unique=False)

    op.drop_table("guardrail_deployment_rule")
    op.drop_table("guardrail_deployment_probes")
    op.drop_table("guardrail_deployments")
    op.drop_table("guardrail_rules")
    op.drop_table("guardrail_probes")

    op.add_column(
        "provider",
        sa.Column(
            "capabilities",
            postgresql.ARRAY(
                postgresql.ENUM("model", "moderation", name="provider_capability_enum", create_type=False)
            ),
            nullable=True,
        ),
    )

    sa.Enum("endpoint_mapped", "standalone", name="guardrail_deployment_type").drop(op.get_bind())
    op.sync_enum_values(
        enum_schema="public",
        enum_name="guardrail_provider_type_enum",
        new_values=["cloud", "bud"],
        affected_columns=[
            TableReference(table_schema="public", table_name="guardrail_probe", column_name="provider_type")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="guardrail_provider_type_enum",
        new_values=["cloud_provider", "bud_sentinel"],
        affected_columns=[
            TableReference(table_schema="public", table_name="guardrail_probe", column_name="provider_type")
        ],
        enum_values_to_rename=[],
    )
    sa.Enum("endpoint_mapped", "standalone", name="guardrail_deployment_type").create(op.get_bind())
    op.drop_column("provider", "capabilities")

    op.create_table(
        "guardrail_deployment_probes",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("deployment_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("probe_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("is_enabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("threshold_override", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("modified_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["guardrail_deployments.id"],
            name="guardrail_deployment_probes_deployment_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["probe_id"], ["guardrail_probes.id"], name="guardrail_deployment_probes_probe_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="guardrail_deployment_probes_pkey"),
        sa.UniqueConstraint(
            "deployment_id",
            "probe_id",
            name="uq_deployment_probe",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        postgresql_ignore_search_path=False,
    )

    op.create_table(
        "guardrail_probes",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("sentinel_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("provider_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "provider_type",
            postgresql.ENUM("cloud_provider", "bud_sentinel", name="guardrail_provider_type_enum", create_type=False),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("is_custom", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("created_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("project_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("modified_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["user.id"], name="guardrail_probes_created_by_fkey", ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["project.id"], name="guardrail_probes_project_id_fkey", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"], ["provider.id"], name="guardrail_probes_provider_id_fkey", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="guardrail_probes_user_id_fkey", ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name="guardrail_probes_pkey"),
        sa.UniqueConstraint(
            "name", name="guardrail_probes_name_key", postgresql_include=[], postgresql_nulls_not_distinct=False
        ),
        postgresql_ignore_search_path=False,
    )

    op.create_table(
        "guardrail_deployment_rule",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("deployment_probe_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("rule_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("is_enabled", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("threshold_override", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("modified_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_probe_id"],
            ["guardrail_deployment_probes.id"],
            name=op.f("guardrail_deployment_rule_deployment_probe_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rule_id"],
            ["guardrail_rules.id"],
            name=op.f("guardrail_deployment_rule_rule_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("guardrail_deployment_rule_pkey")),
        sa.UniqueConstraint(
            "deployment_probe_id",
            "rule_id",
            name=op.f("uq_deployment_probe_rule"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )

    op.create_table(
        "guardrail_deployments",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "deployment_type",
            postgresql.ENUM("endpoint_mapped", "standalone", name="guardrail_deployment_type", create_type=False),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("endpoint_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "running",
                "failure",
                "deploying",
                "unhealthy",
                "deleting",
                "deleted",
                "pending",
                name="guardrail_deployment_status",
                create_type=False,
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.Column("default_threshold", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("guardrail_types", postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("project_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column("modified_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["endpoint_id"], ["endpoint.id"], name=op.f("guardrail_deployments_endpoint_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["project.id"], name=op.f("guardrail_deployments_project_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("guardrail_deployments_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("guardrail_deployments_pkey")),
    )

    op.drop_index(op.f("ix_guardrail_profile_rule_rule_id"), table_name="guardrail_profile_rule")
    op.drop_table("guardrail_profile_rule")
    op.drop_table("guardrail_deployment")
    op.drop_index(op.f("ix_guardrail_rule_probe_id"), table_name="guardrail_rule")
    op.drop_table("guardrail_rule")
    op.drop_index(op.f("ix_guardrail_profile_probe_probe_id"), table_name="guardrail_profile_probe")
    op.drop_table("guardrail_profile_probe")
    op.drop_table("guardrail_profile")
    op.drop_table("guardrail_probe")
    sa.Enum("model", "moderation", name="provider_capability_enum").drop(op.get_bind())
    sa.Enum("active", "disabled", "deleted", name="guardrail_status_enum").drop(op.get_bind())
    # ### end Alembic commands ###
