"""Update proprietary credential types

Revision ID: 27aaabdf2b63
Revises: de33c215c978
Create Date: 2025-09-15 19:33:46.487734

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "27aaabdf2b63"
down_revision: Union[str, None] = "de33c215c978"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "guardrail_deployment", "proprietary_credential", ["credential_id"], ["id"])
    op.sync_enum_values(
        enum_schema="public",
        enum_name="proprietary_credential_type_enum",
        new_values=[
            "nlp_cloud",
            "deepinfra",
            "anthropic",
            "vertex_ai-vision-models",
            "vertex_ai-ai21_models",
            "cerebras",
            "watsonx",
            "predibase",
            "volcengine",
            "clarifai",
            "baseten",
            "sambanova",
            "github",
            "petals",
            "replicate",
            "vertex_ai-chat-models",
            "azure_ai",
            "perplexity",
            "vertex_ai-code-text-models",
            "vertex_ai-text-models",
            "cohere_chat",
            "vertex_ai-embedding-models",
            "text-completion-openai",
            "groq",
            "openai",
            "aleph_alpha",
            "sagemaker",
            "databricks",
            "fireworks_ai",
            "vertex_ai-anthropic_models",
            "vertex_ai-mistral_models",
            "voyage",
            "vertex_ai-language-models",
            "anyscale",
            "deepseek",
            "vertex_ai-image-models",
            "mistral",
            "ollama",
            "cohere",
            "gemini",
            "friendliai",
            "vertex_ai-code-chat-models",
            "azure",
            "codestral",
            "vertex_ai-llama_models",
            "together_ai",
            "cloudflare",
            "ai21",
            "openrouter",
            "bedrock",
            "text-completion-codestral",
            "huggingface",
            "bud_sentinel",
            "azure_content_safety",
            "aws_comprehend",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="proprietary_credential", column_name="type")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="proprietary_credential_type_enum",
        new_values=[
            "nlp_cloud",
            "deepinfra",
            "anthropic",
            "vertex_ai-vision-models",
            "vertex_ai-ai21_models",
            "cerebras",
            "watsonx",
            "predibase",
            "volcengine",
            "clarifai",
            "baseten",
            "sambanova",
            "github",
            "petals",
            "replicate",
            "vertex_ai-chat-models",
            "azure_ai",
            "perplexity",
            "vertex_ai-code-text-models",
            "vertex_ai-text-models",
            "cohere_chat",
            "vertex_ai-embedding-models",
            "text-completion-openai",
            "groq",
            "openai",
            "aleph_alpha",
            "sagemaker",
            "databricks",
            "fireworks_ai",
            "vertex_ai-anthropic_models",
            "vertex_ai-mistral_models",
            "voyage",
            "vertex_ai-language-models",
            "anyscale",
            "deepseek",
            "vertex_ai-image-models",
            "mistral",
            "ollama",
            "cohere",
            "gemini",
            "friendliai",
            "vertex_ai-code-chat-models",
            "azure",
            "codestral",
            "vertex_ai-llama_models",
            "together_ai",
            "cloudflare",
            "ai21",
            "openrouter",
            "bedrock",
            "text-completion-codestral",
            "huggingface",
        ],
        affected_columns=[
            TableReference(table_schema="public", table_name="proprietary_credential", column_name="type")
        ],
        enum_values_to_rename=[],
    )
    op.drop_constraint(None, "guardrail_deployment", type_="foreignkey")
    # ### end Alembic commands ###
