"""Added prompt creation workflow

Revision ID: 601f108926d4
Revises: cff39db54e42
Create Date: 2025-08-18 14:16:49.317155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '601f108926d4'
down_revision: Union[str, None] = 'cff39db54e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='workflow_type_enum',
        new_values=['model_deployment', 'model_security_scan', 'cluster_onboarding', 'cluster_deletion', 'endpoint_deletion', 'endpoint_worker_deletion', 'cloud_model_onboarding', 'local_model_onboarding', 'add_worker_to_endpoint', 'license_faq_fetch', 'local_model_quantization', 'model_benchmark', 'add_adapter', 'delete_adapter', 'evaluation_creation', 'prompt_creation'],
        affected_columns=[TableReference(table_schema='public', table_name='workflow', column_name='workflow_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='workflow_type_enum',
        new_values=['model_deployment', 'model_security_scan', 'cluster_onboarding', 'cluster_deletion', 'endpoint_deletion', 'endpoint_worker_deletion', 'cloud_model_onboarding', 'local_model_onboarding', 'add_worker_to_endpoint', 'license_faq_fetch', 'local_model_quantization', 'model_benchmark', 'add_adapter', 'delete_adapter', 'evaluation_creation'],
        affected_columns=[TableReference(table_schema='public', table_name='workflow', column_name='workflow_type')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
