"""Added metadata to prompt version

Revision ID: 8a9b463c9646
Revises: b4d764550ad9
Create Date: 2025-11-03 07:59:04.792357

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import ColumnType, TableReference
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "8a9b463c9646"
down_revision: Union[str, None] = "b4d764550ad9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prompt_version",
        sa.Column(
            "version_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prompt_version", "version_metadata")
    # ### end Alembic commands ###
