"""Prompt rate limit updated

Revision ID: 904616580637
Revises: c9794f97e17c
Create Date: 2025-09-14 06:46:09.810967

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "904616580637"
down_revision: Union[str, None] = "c9794f97e17c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("prompt", sa.Column("rate_limit", sa.Boolean(), nullable=False))
    op.create_foreign_key(
        None, "prompt", "prompt_version", ["default_version_id"], ["id"], ondelete="SET NULL", use_alter=True
    )
    op.drop_column("prompt", "rate_limit_type")
    sa.Enum("enabled", "disabled", "auto", "custom", name="rate_limit_type_enum").drop(op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("enabled", "disabled", "auto", "custom", name="rate_limit_type_enum").create(op.get_bind())
    op.add_column(
        "prompt",
        sa.Column(
            "rate_limit_type",
            postgresql.ENUM("enabled", "disabled", "auto", "custom", name="rate_limit_type_enum", create_type=False),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint("prompt_default_version_id_fkey", "prompt", type_="foreignkey")
    op.drop_column("prompt", "rate_limit")
    # ### end Alembic commands ###
