"""Prompt Table cluster_id Optional

Revision ID: aea48f780385
Revises: 08a2d54a2f41
Create Date: 2025-09-23 12:29:27.638802

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import ColumnType, TableReference
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "aea48f780385"
down_revision: Union[str, None] = "08a2d54a2f41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("prompt_version", "cluster_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("prompt_version", "cluster_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
