"""project id not null

Revision ID: c82d259d07ce
Revises: 3c1e5f3016b0
Create Date: 2025-08-07 00:43:33.567810

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "c82d259d07ce"
down_revision: Union[str, None] = "3c1e5f3016b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("experiments", "project_id", nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("experiments", "project_id", nullable=False)

    # ### end Alembic commands ###
