"""Removed prompt schema

Revision ID: de33c215c978
Revises: 904616580637
Create Date: 2025-09-15 01:12:47.230666

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "de33c215c978"
down_revision: Union[str, None] = "904616580637"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("prompt_version", "prompt_schema")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "prompt_version",
        sa.Column("prompt_schema", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
