"""Add access mode to cluster settings

Revision ID: e66057c39de4
Revises: b9c8d7e6f5a4
Create Date: 2025-09-29 11:56:32.616059

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic_postgresql_enum import ColumnType, TableReference
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "e66057c39de4"
down_revision: Union[str, None] = "b9c8d7e6f5a4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cluster_settings", sa.Column("default_access_mode", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("cluster_settings", "default_access_mode")
    # ### end Alembic commands ###
