"""Add storage_size_gb to model

Revision ID: f5b76a5c7bda
Revises: 8a9b463c9646
Create Date: 2025-01-18 00:00:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f5b76a5c7bda"
down_revision: Union[str, None] = "8a9b463c9646"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "model",
        sa.Column("storage_size_gb", sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model", "storage_size_gb")
    # ### end Alembic commands ###
