imagePullSecrets:
    - name: harbor-bud

global:
    ingress:
        hosts:
            root: "dev.bud.studio"

ingress:
    https: internal

storage:
    budmodelRegistry:
        size: "1Ti"

minio:
    persistence:
        size: "1Ti"

microservices:
    budadmin:
        env:
            NEXT_PUBLIC_ENABLE_DEV_MODE: "true"
        image: budstudio/budadmin:nightly
    budcustomer:
        image: budstudio/budcustomer:nightly
    budplayground:
        image: budstudio/budplayground:nightly
    budgateway:
        image: budstudio/budgateway:nightly
        resources:
            limits:
                cpu: 500m
                memory: 1024Mi
            requests:
                cpu: 250m
                memory: 512Mi
    askbud:
        image: budstudio/askbud:nightly
    budapp:
        image: budstudio/budapp:nightly
        env:
            RATE_LIMIT_ENABLED: "false"
    budcluster:
        image: budstudio/budcluster:nightly
    budmetrics:
        image: budstudio/budmetrics:nightly
    budmodel:
        image: budstudio/budmodel:nightly
    budeval:
        image: budstudio/budeval:nightly
    budsim:
        image: budstudio/budsim:nightly
    buddoc:
        image: budstudio/buddoc:nightly
    budnotify:
        image: budstudio/budnotify:nightly
    budsentinel:
        enabled: true
        resources:
            limits:
                cpu: 500m
                memory: 1024Mi
            requests:
                cpu: 250m
                memory: 512Mi
    mcpgateway:
        resources:
            limits:
                cpu: 500m
                memory: 1024Mi
            requests:
                cpu: 250m
                memory: 512Mi
    budprompt:
        image: budstudio/budprompt:nightly
        env:
            LOG_LEVEL: DEBUG
    budpipeline:
        image: budstudio/budpipeline:nightly

imagePullPolicy: "Always"
deploymentAnnotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/match-tag: true
    keel.sh/pollSchedule: "@every 1m"
