"""modified leaderboard model

Revision ID: 12589717fd38
Revises: 18be3a789785
Create Date: 2025-04-12 11:41:12.447257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12589717fd38'
down_revision: Union[str, None] = '18be3a789785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('SCRAPED', 'README_LLM', name='leaderboarddataorigin').create(op.get_bind())
    op.add_column('leaderboard', sa.Column('eval_name', sa.String(length=100), nullable=False))
    op.add_column('leaderboard', sa.Column('normalised_eval_name', sa.String(length=100), nullable=False))
    op.add_column('leaderboard', sa.Column('eval_score', sa.Float(), nullable=True))
    op.add_column('leaderboard', sa.Column('data_origin', postgresql.ENUM('SCRAPED', 'README_LLM', name='leaderboarddataorigin', create_type=False), nullable=False))
    op.alter_column('leaderboard', 'source_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_leaderboard_eval_name'), 'leaderboard', ['eval_name'], unique=False)
    op.create_index(op.f('ix_leaderboard_normalised_eval_name'), 'leaderboard', ['normalised_eval_name'], unique=False)
    op.drop_column('leaderboard', 'mmstar')
    op.drop_column('leaderboard', 'unruly_score')
    op.drop_column('leaderboard', 'mmmu')
    op.drop_column('leaderboard', 'mmvet')
    op.drop_column('leaderboard', 'mmbench')
    op.drop_column('leaderboard', 'bcfl')
    op.drop_column('leaderboard', 'live_code_bench')
    op.drop_column('leaderboard', 'clustering')
    op.drop_column('leaderboard', 'pair_classification')
    op.drop_column('leaderboard', 'hallucination_bench')
    op.drop_column('leaderboard', 'ocr_bench')
    op.drop_column('leaderboard', 'classification')
    op.drop_column('leaderboard', 'lmsys_areana')
    op.drop_column('leaderboard', 'math_vista')
    op.drop_column('leaderboard', 'polcontro_score')
    op.drop_column('leaderboard', 'w_10_score')
    op.drop_column('leaderboard', 'ai2d')
    op.drop_column('leaderboard', 'retrieval')
    op.drop_column('leaderboard', 'reranking')
    op.drop_column('leaderboard', 'ugi_score')
    op.drop_column('leaderboard', 'lc_win_rate')
    op.drop_column('leaderboard', 'win_rate')
    op.drop_column('leaderboard', 'internet_score')
    op.drop_column('leaderboard', 'semantic')
    op.drop_column('leaderboard', 'summarization')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaderboard', sa.Column('summarization', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('semantic', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('internet_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('win_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('lc_win_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('ugi_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('reranking', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('retrieval', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('ai2d', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('w_10_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('polcontro_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('math_vista', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('lmsys_areana', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('classification', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('ocr_bench', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('hallucination_bench', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('pair_classification', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('clustering', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('live_code_bench', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('bcfl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('mmbench', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('mmvet', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('mmmu', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('unruly_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('leaderboard', sa.Column('mmstar', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_leaderboard_normalised_eval_name'), table_name='leaderboard')
    op.drop_index(op.f('ix_leaderboard_eval_name'), table_name='leaderboard')
    op.alter_column('leaderboard', 'source_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('leaderboard', 'data_origin')
    op.drop_column('leaderboard', 'eval_score')
    op.drop_column('leaderboard', 'normalised_eval_name')
    op.drop_column('leaderboard', 'eval_name')
    sa.Enum('SCRAPED', 'README_LLM', name='leaderboarddataorigin').drop(op.get_bind())
    # ### end Alembic commands ###
