"""Modified license model

Revision ID: 18be3a789785
Revises: 6283654bf634
Create Date: 2025-04-01 06:50:23.870497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18be3a789785'
down_revision: Union[str, None] = '6283654bf634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('license_info', sa.Column('type', sa.Text(), nullable=True))
    op.add_column('license_info', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('license_info', sa.Column('suitability', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('license_info', 'suitability')
    op.drop_column('license_info', 'description')
    op.drop_column('license_info', 'type')
    # ### end Alembic commands ###
