"""Leaderboard Interation Changes

Revision ID: 3ce4f0b95669
Revises: 2e1721a7b9ed
Create Date: 2025-02-04 03:24:31.661929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ce4f0b95669'
down_revision: Union[str, None] = '2e1721a7b9ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('wait_for', sa.Text(), nullable=True),
    sa.Column('js_code', sa.Text(), nullable=True),
    sa.Column('schema', sa.Text(), nullable=True),
    sa.Column('css_base_selector', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_name'), 'source', ['name'], unique=False)
    op.add_column('model_info', sa.Column('id', sa.UUID(), nullable=False))
    op.alter_column('model_info', 'author',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('model_info', 'modality',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('model_info', 'name')
    op.drop_column('model_info', 'model_path')
    op.drop_column('model_info', 'scan_result')
    op.drop_column('model_info', 'provider_type')
    op.create_primary_key(None, 'model_info', ['id'])
    op.create_table('leaderboard',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bcfl', sa.Float(), nullable=True),
    sa.Column('live_code_bench', sa.Float(), nullable=True),
    sa.Column('classification', sa.Float(), nullable=True),
    sa.Column('clustering', sa.Float(), nullable=True),
    sa.Column('pair_classification', sa.Float(), nullable=True),
    sa.Column('reranking', sa.Float(), nullable=True),
    sa.Column('retrieval', sa.Float(), nullable=True),
    sa.Column('semantic', sa.Float(), nullable=True),
    sa.Column('summarization', sa.Float(), nullable=True),
    sa.Column('mmbench', sa.Float(), nullable=True),
    sa.Column('mmstar', sa.Float(), nullable=True),
    sa.Column('mmmu', sa.Float(), nullable=True),
    sa.Column('math_vista', sa.Float(), nullable=True),
    sa.Column('ocr_bench', sa.Float(), nullable=True),
    sa.Column('ai2d', sa.Integer(), nullable=True),
    sa.Column('hallucination_bench', sa.Float(), nullable=True),
    sa.Column('mmvet', sa.Float(), nullable=True),
    sa.Column('lmsys_areana', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('model_info_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_info_id'], ['model_info.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leaderboard')
    op.add_column('model_info', sa.Column('provider_type', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('model_info', sa.Column('scan_result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('model_info', sa.Column('model_path', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('model_info', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('model_info', 'modality',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('model_info', 'author',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('model_info', 'id')
    op.drop_index(op.f('ix_source_name'), table_name='source')
    op.drop_table('source')
    # ### end Alembic commands ###
