"""updated source model

Revision ID: 6283654bf634
Revises: f5254fd166ca
Create Date: 2025-03-31 13:38:52.820220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6283654bf634'
down_revision: Union[str, None] = 'f5254fd166ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('last_extracted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'last_extracted_at')
    # ### end Alembic commands ###
