"""updated model info table

Revision ID: 69ac89bcadaf
Revises: 12589717fd38
Create Date: 2025-04-18 12:36:53.729441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69ac89bcadaf'
down_revision: Union[str, None] = '12589717fd38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_model_info_uri', 'model_info', ['uri'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_model_info_uri', 'model_info', type_='unique')
    # ### end Alembic commands ###
