"""Changed licence_id datatype

Revision ID: 870aca89b7db
Revises: 292e0d554304
Create Date: 2025-05-06 00:05:44.785232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '870aca89b7db'
down_revision: Union[str, None] = '292e0d554304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraint first
    op.drop_constraint('model_info_license_id_fkey', 'model_info', type_='foreignkey')

    op.drop_constraint('license_info_id_key', 'license_info', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('license_info_id_key', 'license_info', ['id'])

    # Then recreate foreign key constraint
    op.create_foreign_key(
        'model_info_license_id_fkey',
        'model_info', 'license_info',
        ['license_id'], ['id']
    )
    # ### end Alembic commands ###
