"""Updated leaderboard table

Revision ID: f5254fd166ca
Revises: f88c8542472e
Create Date: 2025-02-21 07:04:21.890662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5254fd166ca'
down_revision: Union[str, None] = 'f88c8542472e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaderboard', sa.Column('lc_win_rate', sa.Float(), nullable=True))
    op.add_column('leaderboard', sa.Column('win_rate', sa.Float(), nullable=True))
    op.add_column('leaderboard', sa.Column('ugi_score', sa.Float(), nullable=True))
    op.add_column('leaderboard', sa.Column('w_10_score', sa.Float(), nullable=True))
    op.add_column('leaderboard', sa.Column('unruly_score', sa.Float(), nullable=True))
    op.add_column('leaderboard', sa.Column('internet_score', sa.Float(), nullable=True))
    op.add_column('leaderboard', sa.Column('polcontro_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaderboard', 'polcontro_score')
    op.drop_column('leaderboard', 'internet_score')
    op.drop_column('leaderboard', 'unruly_score')
    op.drop_column('leaderboard', 'w_10_score')
    op.drop_column('leaderboard', 'ugi_score')
    op.drop_column('leaderboard', 'win_rate')
    op.drop_column('leaderboard', 'lc_win_rate')
    # ### end Alembic commands ###
