"""updated cluster table.

Revision ID: b2b4006ae814
Revises: bc229dbb32c9
Create Date: 2024-10-22 10:08:45.069209

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b2b4006ae814"
down_revision: Union[str, None] = "bc229dbb32c9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("kubernetes", "openshift", name="cluster_platform_enum").create(op.get_bind())
    with op.batch_alter_table("cluster", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("platform", sa.Enum("kubernetes", "openshift", name="cluster_platform_enum"), nullable=False)
        )
        batch_op.add_column(sa.Column("kube_nodes", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("threads_per_core", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("core_count", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("enable_master_node", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("reason", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cluster", schema=None) as batch_op:
        batch_op.drop_column("reason")
        batch_op.drop_column("enable_master_node")
        batch_op.drop_column("core_count")
        batch_op.drop_column("threads_per_core")
        batch_op.drop_column("kube_nodes")
        batch_op.drop_column("platform")
    sa.Enum("kubernetes", "openshift", name="cluster_platform_enum").drop(op.get_bind())

    # ### end Alembic commands ###
