"""remove is_active, add ondelete cascade.

Revision ID: f502efba4ac3
Revises: 41161f061631
Create Date: 2024-11-29 11:58:33.280089

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f502efba4ac3"
down_revision: Union[str, None] = "41161f061631"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cluster", schema=None) as batch_op:
        batch_op.drop_column("is_active")

    with op.batch_alter_table("cluster_node_info", schema=None) as batch_op:
        batch_op.drop_constraint("fk_cluster_node_info_cluster_id_cluster", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_cluster_node_info_cluster_id_cluster"),
            "cluster",
            ["cluster_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cluster_node_info", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_cluster_node_info_cluster_id_cluster"), type_="foreignkey")
        batch_op.create_foreign_key("fk_cluster_node_info_cluster_id_cluster", "cluster", ["cluster_id"], ["id"])

    with op.batch_alter_table("cluster", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
