"""removed total_nodes from cluster table.

Revision ID: b8b152df45f4
Revises: 1eb08efe27b4
Create Date: 2024-10-26 06:30:30.416168

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b8b152df45f4"
down_revision: Union[str, None] = "1eb08efe27b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cluster", schema=None) as batch_op:
        batch_op.drop_column("total_nodes")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cluster", schema=None) as batch_op:
        batch_op.add_column(sa.Column("total_nodes", sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
