"""removed created_by from cluster table.

Revision ID: 41161f061631
Revises: 187f3144de45
Create Date: 2024-11-08 11:05:01.266522

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "41161f061631"
down_revision: Union[str, None] = "187f3144de45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cluster", schema=None) as batch_op:
        batch_op.alter_column("ingress_url", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.drop_column("created_by")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cluster", schema=None) as batch_op:
        batch_op.alter_column("ingress_url", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.add_column(sa.Column("created_by", sa.UUID(), nullable=False))
    # ### end Alembic commands ###
