"""added created_by to cluster model.

Revision ID: 1eb08efe27b4
Revises: b2b4006ae814
Create Date: 2024-10-22 10:17:36.177347

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "1eb08efe27b4"
down_revision: Union[str, None] = "b2b4006ae814"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cluster", schema=None) as batch_op:
        batch_op.add_column(sa.Column("created_by", sa.Uuid(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cluster", schema=None) as batch_op:
        batch_op.drop_column("created_by")

    # ### end Alembic commands ###
