"""cluster_node_info table added.

Revision ID: 48a9a897ec17
Revises: b8b152df45f4
Create Date: 2024-10-29 07:57:42.325882

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "48a9a897ec17"
down_revision: Union[str, None] = "b8b152df45f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cluster_node_info",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cluster_id", sa.Uuid(), nullable=False),
        sa.Column("node_info", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["cluster_id"], ["cluster.id"], name=op.f("fk_cluster_node_info_cluster_id_cluster")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cluster_node_info")),
    )
    with op.batch_alter_table("cluster", schema=None) as batch_op:
        batch_op.alter_column(
            "kubernetes_metadata",
            existing_type=sa.VARCHAR(),
            type_=postgresql.JSONB(astext_type=sa.Text()),
            postgresql_using="kubernetes_metadata::jsonb",
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cluster", schema=None) as batch_op:
        batch_op.alter_column(
            "kubernetes_metadata",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    op.drop_table("cluster_node_info")
    # ### end Alembic commands ###
