"""added device name to worker_info table.

Revision ID: 5a6d4ee8ef06
Revises: 3e54b2221a62
Create Date: 2025-01-28 06:10:24.104865

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "5a6d4ee8ef06"
down_revision: Union[str, None] = "3e54b2221a62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("worker_info", schema=None) as batch_op:
        batch_op.add_column(sa.Column("device_name", sa.String(), nullable=False))
        batch_op.alter_column(
            "created_datetime",
            existing_type=sa.VARCHAR(),
            type_=sa.DateTime(),
            existing_nullable=False,
            postgresql_using="created_datetime::timestamp",
        )
        batch_op.alter_column(
            "last_restart_datetime",
            existing_type=sa.VARCHAR(),
            type_=sa.DateTime(),
            existing_nullable=False,
            postgresql_using="last_restart_datetime::timestamp",
        )
        batch_op.alter_column(
            "last_updated_datetime",
            existing_type=sa.VARCHAR(),
            type_=sa.DateTime(),
            existing_nullable=False,
            postgresql_using="last_updated_datetime::timestamp",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("worker_info", schema=None) as batch_op:
        batch_op.alter_column(
            "last_updated_datetime", existing_type=sa.DateTime(), type_=sa.VARCHAR(), existing_nullable=False
        )
        batch_op.alter_column(
            "last_restart_datetime", existing_type=sa.DateTime(), type_=sa.VARCHAR(), existing_nullable=False
        )
        batch_op.alter_column(
            "created_datetime", existing_type=sa.DateTime(), type_=sa.VARCHAR(), existing_nullable=False
        )
        batch_op.drop_column("device_name")

    # ### end Alembic commands ###
