"""NFD feilds.

Revision ID: 3bc055340c00
Revises: a55cf07f6ef7
Create Date: 2025-08-19 07:13:24.403754

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "3bc055340c00"
down_revision: Union[str, None] = "a55cf07f6ef7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cluster_node_info", schema=None) as batch_op:
        batch_op.add_column(sa.Column("schedulable", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("unschedulable", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("taints", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column("conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column("pressure_conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column("nfd_detected", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("nfd_labels", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column("detection_method", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("kernel_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column("driver_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table("worker_info", schema=None) as batch_op:
        batch_op.alter_column("device_name", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("worker_info", schema=None) as batch_op:
        batch_op.alter_column("device_name", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("cluster_node_info", schema=None) as batch_op:
        batch_op.drop_column("driver_info")
        batch_op.drop_column("kernel_info")
        batch_op.drop_column("detection_method")
        batch_op.drop_column("nfd_labels")
        batch_op.drop_column("nfd_detected")
        batch_op.drop_column("pressure_conditions")
        batch_op.drop_column("conditions")
        batch_op.drop_column("taints")
        batch_op.drop_column("unschedulable")
        batch_op.drop_column("schedulable")

    # ### end Alembic commands ###
