"""cluster_id foreign key in worker info table.

Revision ID: 6f7574a672fc
Revises: 76aadd6718e4
Create Date: 2025-01-14 07:48:15.797135

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "6f7574a672fc"
down_revision: Union[str, None] = "76aadd6718e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    # add constraint on cluster_id in worker_info table and make it foreign key to cluster table
    op.create_foreign_key(
        "fk_worker_info_cluster_id", "worker_info", "cluster", ["cluster_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_worker_info_cluster_id", "worker_info", type_="foreignkey")
    # ### end Alembic commands ###
