"""added WorkerInfo table.

Revision ID: 76aadd6718e4
Revises: 80d3f71fd371
Create Date: 2025-01-09 18:51:37.676624

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "76aadd6718e4"
down_revision: Union[str, None] = "80d3f71fd371"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("Pending", "Running", "Succeeded", "Failed", "Unknown", name="worker_status_enum").create(op.get_bind())
    sa.Enum("ready", "pending", "ingress_failed", "failed", name="deployment_status_enum").create(op.get_bind())
    op.create_table(
        "worker_info",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("cluster_id", sa.Uuid(), nullable=False),
        sa.Column("namespace", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("node_ip", sa.String(), nullable=False),
        sa.Column("node_name", sa.String(), nullable=False),
        sa.Column("utilization", sa.String(), nullable=True),
        sa.Column("hardware", sa.String(), nullable=False),
        sa.Column("uptime", sa.String(), nullable=False),
        sa.Column("created_date", sa.String(), nullable=False),
        sa.Column("last_restart_date", sa.String(), nullable=False),
        sa.Column("last_updated_date", sa.String(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "Pending", "Running", "Succeeded", "Failed", "Unknown", name="worker_status_enum", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("cores", sa.Integer(), nullable=False),
        sa.Column("memory", sa.String(), nullable=False),
        sa.Column(
            "deployment_status",
            postgresql.ENUM(
                "ready", "pending", "ingress_failed", "failed", name="deployment_status_enum", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("worker_info")
    sa.Enum("Pending", "Running", "Succeeded", "Failed", "Unknown", name="worker_status_enum").drop(op.get_bind())
    sa.Enum("ready", "pending", "ingress_failed", "failed", name="deployment_status_enum").drop(op.get_bind())
    # ### end Alembic commands ###
