"""change column types in worker_info.

Revision ID: 93e068c23299
Revises: d4774e057a42
Create Date: 2025-01-16 04:44:06.011522

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "93e068c23299"
down_revision: Union[str, None] = "d4774e057a42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("worker_info", "last_restart_date", new_column_name="last_restart_datetime")
    op.alter_column("worker_info", "last_updated_date", new_column_name="last_updated_datetime")
    op.alter_column("worker_info", "created_date", new_column_name="created_datetime")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("worker_info", "last_restart_datetime", new_column_name="last_restart_date")
    op.alter_column("worker_info", "last_updated_datetime", new_column_name="last_updated_date")
    op.alter_column("worker_info", "created_datetime", new_column_name="created_date")
    # ### end Alembic commands ###
