"""deployment_name column added.

Revision ID: d4774e057a42
Revises: 6f7574a672fc
Create Date: 2025-01-14 16:32:09.655545

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d4774e057a42"
down_revision: Union[str, None] = "6f7574a672fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("worker_info", sa.Column("deployment_name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("worker_info", "deployment_name")
    # ### end Alembic commands ###
