FROM python:3.11.0

WORKDIR /app
COPY requirements.txt /app/

RUN mkdir /app/scripts
COPY scripts/migrate_clickhouse.py /app/scripts
COPY scripts/startup.sh /app/scripts

RUN pip install --upgrade pip
RUN pip install -r ./requirements.txt