"""add engine metadata fields

Revision ID: 7e31f2b8c4d9
Revises: 2f9d64e993a7
Create Date: 2025-09-25 16:20:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e31f2b8c4d9'
down_revision: Union[str, None] = '2f9d64e993a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_results', sa.Column('engine_version', sa.String(length=50), nullable=True))
    op.add_column('simulation_results', sa.Column('tool_calling_parser_type', sa.String(length=100), nullable=True))
    op.add_column('simulation_results', sa.Column('reasoning_parser_type', sa.String(length=100), nullable=True))
    op.add_column('simulation_results', sa.Column('architecture_family', sa.String(length=100), nullable=True))
    op.add_column('simulation_results', sa.Column('chat_template', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_results', 'chat_template')
    op.drop_column('simulation_results', 'architecture_family')
    op.drop_column('simulation_results', 'reasoning_parser_type')
    op.drop_column('simulation_results', 'tool_calling_parser_type')
    op.drop_column('simulation_results', 'engine_version')
    # ### end Alembic commands ###
