"""engine image

Revision ID: 9bcbbad43111
Revises: 5d9b73ed7744
Create Date: 2025-05-12 07:22:03.238257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bcbbad43111'
down_revision: Union[str, None] = '5d9b73ed7744'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simulation_results', sa.Column('engine_image', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('simulation_results', 'engine_image')
    # ### end Alembic commands ###
